version: '3'
services:
  randolivetiles:
    build: 
        context: .
        dockerfile: ./docker-randolivetiles
    ports:
    - "12401:9000"
  hdfsup:
    build: 
        context: .
        dockerfile: ./docker-hdfsup
    ports:
    - "12402:8763"
    volumes:
       - tuiles:/tuiles
volumes:
  tuiles:


