version: '3'
services:
  randolivetiles:
    env_file:
      - .env
    build: 
        context: .
        dockerfile: ./docker-randolivetiles
    ports:
      - "12401:9000"
    links:
      - elastic:elastic
    depends_on:
      - elastic
  hdfsup:
    env_file:
      - .env
    build: 
        context: .
        dockerfile: ./docker-hdfsup
    ports:
      - "12402:8763"
    volumes:
       - tuiles:/tuiles
       - ./ssh:/root/.ssh
  satiles:
    env_file:
      - .env
    build: 
        context: .
        dockerfile: ./docker-satiles
    ports:
      - "12403:8080"
    volumes:
       - tuiles:/tuiles
  elastic:
    image: elasticsearch:6.7.0
    ports:
      - "9300:9300"
      - "9200:9200"
volumes:
  tuiles:


